#plugins:
#  - examples.bogusdatasource

datasources:
  petals:
    type: csv
    path: ./private/iris_train.csv  # The string can also be a URL. Valid URL schemes include http, ftp, s3, and file.
    expires: 0  # -1: never (=cached forever), 0: immediately (=no caching), >0: time in seconds.
    options: {}
    tags: train
  petals_test:
    type: csv
    path: ./private/iris_holdout.csv  # The string can also be a URL. Valid URL schemes include http, ftp, s3, and file.
    expires: 3600  # -1: never (=cached forever), 0: immediately (=no caching), >0: time in seconds.
    options: {}
    tags: test

model_store:
  location: model_store  # TODO: maybe support sftp or other remote locations...

model:
  name: IrisModel
  version: '0.0.5'  # use semantic versioning (<breaking>.<adding>.<fix>)
  module: app.model  # same as file name without .py
  train_options: {}
  predict_options: {}

api:
  name: iris  # name of the service api
  version: '0.0.5'  # use semantic versioning (breaking.adding.fix), first segment will be used in url as e.g. .../v1/...
  raml: api.raml
  preload_datasources: True  # Load datasources into memory before any predictions. Only makes sense with caching.
  root_path: .  # (optional) set directory where Flask should look for the directories `static` and `templates` to serve.

deploy:
  include: # Files/patterns that should be added to the zipped deployment artifact. Uses recursion.
    - app/*
    - '*.yml'
    - '*.raml'
    - wheels/*
    - model_store/*
  exclude:  # Exclude files with any of these strings in their path
    - __pycache__
    - config_tpl.yml
    - config_dev.yml
  requirements:
    file: requirements_frozen.txt  # Please use frozen requirements for reproducibility. How to create: https://github.com/schuderer/mllaunchpad/issues/60
    platform: manylinux1_x86_64  # will have to transition to manylinux2010 some time in the future (supported by pip>=19.0)
    save_to: wheels
    vulnerability_db: C:/dev/python_vulnerability_db  # If empty string "", tries to get information from pyup's safety-db website (source: https://raw.githubusercontent.com/pyupio/safety-db/master/data/)
    pip_index_url: ""  # Empty string "" to use the default (which is usually pypi.org, but depends on your pip config).
    pip_trusted_hosts: []  # WARNING: Only ever use when told to use, and even then only as an exception, and only for hosts in the local network!
  python: '3.6'
  deployment_requires: []

